# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'get_latest_by': 'email', 'ordering': ('-email',)},
        ),
        migrations.AlterField(
            model_name='entry',
            name='surname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
