# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0002_auto_20170716_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('mobile', models.CharField(error_messages={'blank': 'This field is cannot be empty, please try again.', 'unique': 'This Mobile Number is not unique, please try again.'}, help_text='Must be a unique Mobile Number.', max_length=30, unique=True, verbose_name='Mobile Number')),
                ('address', models.CharField(max_length=80)),
                ('email', models.EmailField(error_messages={'blank': 'This field is cannot be empty, please try again.', 'unique': 'This e-mail address is not unique, please try again.'}, help_text='Must be a unique e-mail address.', max_length=254, unique=True)),
            ],
            options={
                'ordering': ('-email',),
                'get_latest_by': 'email',
            },
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
